### ISSUE TITLE
Accommodation Advertisement - Add further description

### ISSUE THREAD

**Issue by ScientistCoco** [unsw-cse-comp3900-9900/capstone-project-strength-in-numbers#5]
As an accommodation owner I want to be able to add a description of the accommodation so that I can add extra info to entice prospective customers

**Description**:
This user story provides information on the 'Description' field of the accommodation form. 

**Link to design**: https://www.figma.com/file/Ca4KLEsTGAbaYCTS2t72mNJF/Accommodation-Posting?node-id=3%3A295

**Acceptance Criteria**:
- [x] GIVEN I am on the Photo section
WHEN I click 'Continue'
THEN I should be navigated to the Description section
AND I should see a textfield where I can enter textual information about my accommodation
- [x] GIVEN I am on the Description section
WHEN I click 'Continue'
THEN I should be navigated to the Completed page

**Comment by limittox** [comment]
- [ ] Need to add icon 
- [ ] Need to change css
